### ISSUE TITLE
Need to fix the redirect when the hidden form fields have content

### ISSUE THREAD

**Issue by tvb** [tvb/Honeypot#1]
I think we need to do some redirecting here (https://github.com/tvb/Honeypot/blob/master/plugin.php#L38) but had trouble implementing it correctly.

**Comment by tobscure** [comment]
I think you'd want to do it in processHoneypotField? Instead of returning false, just send a Location header

**Comment by tvb** [comment]
Hmmm I was trying to use the $sender/$controller->redirectURL, but yeah simple header location would work..

**Comment by tobscure** [comment]
Or use the global redirect function: https://github.com/esotalk/esoTalk/blob/develop/core/lib/functions.general.php#L828

**Comment by tvb** [comment]
Oh heh. Thanks I will update the plugin asap.

**Comment by tvb** [comment]
Fixed it. Thank @tobscure
